// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabMSfv5xxRltg1BzF3-kHdQ5tHW1WJG0',
    appId: '1:893503311325:web:f9b9fc1fecee18b8af7a34',
    messagingSenderId: '893503311325',
    projectId: 'voyage-f65e4',
    authDomain: 'voyage-f65e4.firebaseapp.com',
    storageBucket: 'voyage-f65e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6of4n2TbqHoYPZpb5ev1JGkcv-6i-GRw',
    appId: '1:893503311325:android:da5e6abcb459b2beaf7a34',
    messagingSenderId: '893503311325',
    projectId: 'voyage-f65e4',
    storageBucket: 'voyage-f65e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ZF_eQn6X6qIUc1scvwvKOVYmN6re1mE',
    appId: '1:893503311325:ios:bdb493647a74640aaf7a34',
    messagingSenderId: '893503311325',
    projectId: 'voyage-f65e4',
    storageBucket: 'voyage-f65e4.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ZF_eQn6X6qIUc1scvwvKOVYmN6re1mE',
    appId: '1:893503311325:ios:bdb493647a74640aaf7a34',
    messagingSenderId: '893503311325',
    projectId: 'voyage-f65e4',
    storageBucket: 'voyage-f65e4.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabMSfv5xxRltg1BzF3-kHdQ5tHW1WJG0',
    appId: '1:893503311325:web:2a550282ab7e67a0af7a34',
    messagingSenderId: '893503311325',
    projectId: 'voyage-f65e4',
    authDomain: 'voyage-f65e4.firebaseapp.com',
    storageBucket: 'voyage-f65e4.firebasestorage.app',
  );
}
